apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: kubernetes
    - name: duration 
      value: 20hrs 
    resources:
      requests:
        cpu: 100m 
        memory: 250Mi
      limits:
        cpu: 100m 
        memory: 250Mi 

 