apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
data:
  username: "YWRtaW4K"
  password: "YWRtaW4xMjMK"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: nginx-secrets
      image: nginx
      envFrom:
        - secretRef:
            name: pod-secret
