apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    name: nginx
    app: expense-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    name: nginx
    app: expense-nginx
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx

    