apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    name: nginx
    app: expense-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 32160
---


apiVersion: v1
kind: Pod
metadata:
  name: nginx-np
  labels:
    name: nginx
    app: expense-nginx
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx

    
