apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: Nodeport
  selector:
    name: nginx
    app: expense-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 32160
  