apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-deployment
  labels:
    app: expense
spec:
  replicas: 5
  selector:
    matchLabels:
      app: expense-deploy
      tier: web
   
  template:
    metadata:
      labels:
        app: expense-deploy
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx:stable-perl
          ports:
            - containerPort: 80
    