apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-dynamic
    project: expense
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: persistent-storage
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic
    project: expense
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


